name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true
      - name: dependencies
        run: |
          go mod download
      - name: run test
        run: |
          go test
